project:
  type: website
  output-dir: docs
  preview:
    port: 5100

website:
  title: "SWINNO Codebook"
  repo-url: https://github.com/swinnoproject/living_codebook
  repo-actions: [edit, issue]
  navbar:
    right:
      - about.qmd
      - codebook.qmd
  sidebar:
    style: docked
    contents:
      - section: Innovation
        contents:
        - text: Innovation Table
          href: structured/innovation.qmd
        - text: Exploiter
          href: structured/exploiter.qmd
        - text: Origin
          href: structured/origin.qmd
        - text: Spin-off
          href: structured/spinoff.qmd
        - text: Technological Knowhow
          href: structured/tech_know.qmd
        - text: User Sector
          href: structured/use_sector.qmd
        - section: Innovation Fields
          contents: structured/innovation/*qmd

      - section: Entity
        contents:
        - text: Entity Table
          href: structured/entity.qmd
        - text: Innovation to Entity Table
          href: structured/innovation_entity.qmd
        - section: Entity Fields
          contents: structured/entity/*qmd


      - section: Article
        contents:
        - text: Article Table
          href: structured/article.qmd
        - text: Innovation to Article Table
          href: structured/innovation_article.qmd
        - section: Article Fields
          contents: structured/article/*qmd
  page-footer:
    background: "#161324"
    left: |
      Copyright &copy;  2023 [SWINNO Project](https://www.swedishinnovationdata.se)
    # center:
    #     - href: https://github.com/swinnoproject
    #       icon: github
    #       aria-label: GitHub
    center: |
      *V0.0.2*

    right: |
      [Terms and Conditions](/tscs.qmd)



format:
  html:
    theme: [lux, bw.scss, archivo.scss]
    css: styles.css
    toc: true
    grid:
      body-width: 750px
    margin-width: 250
